#ifndef _THEME_H_
#define _THEME_H_

#include "Common/colors.h"

#define CURSOR_COLOR COLOR_WHITE

#define FRUIT_COLOR COLOR_RED 
#define WALL_COLOR COLOR_GREEN
#define PACMAN_COLOR COLOR_YELLOW
#define GHOST_COLOR COLOR_MAGENTA
#define EMPTY_COLOR COLOR_BLACK
#define PATH_COLOR COLOR_BLUE
#define FRAME_COLOR COLOR_WHITE
#define TEXT_COLOR COLOR_YELLOW
#define ERROR_COLOR (COLOR_BACKGROUND_RED | COLOR_WHITE);

#define WEEK_GHOST_COLOR COLOR_CYAN
#define MESSAGEBOX_COLOR COLOR_YELLOW

#define CHOOSE_SLEEP_TIME 300
#define MOVE_SLEEP_TIME 30
#define PRINT_SLEEP_TIME 30
#define ERASE_SLEEP_TIME 0
#define FINISH_SLEEP_TIME 300

#endif