#ifndef _COLORS_H_
#define _COLORS_H_

#include "platform.h"

#include <windows.h>
#include <wincon.h>

// colors are according to the following table:
// https://msdn.microsoft.com/en-us/library/windows/desktop/ms682088(v=vs.85).aspx

#define COLOR_BLACK 0
#define COLOR_BLUE FOREGROUND_BLUE
#define COLOR_GREEN FOREGROUND_GREEN
#define COLOR_CYAN (FOREGROUND_BLUE | FOREGROUND_GREEN)
#define COLOR_RED FOREGROUND_RED
#define COLOR_MAGENTA (FOREGROUND_RED | FOREGROUND_BLUE)
#define COLOR_YELLOW (FOREGROUND_RED | FOREGROUND_GREEN)
#define COLOR_WHITE (FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE)

#define COLOR_BACKGROUND_BLACK 0
#define COLOR_BACKGROUND_BLUE BACKGROUND_BLUE
#define COLOR_BACKGROUND_GREEN BACKGROUND_GREEN
#define COLOR_BACKGROUND_CYAN (BACKGROUND_BLUE | BACKGROUND_GREEN)
#define COLOR_BACKGROUND_RED BACKGROUND_RED
#define COLOR_BACKGROUND_MAGENTA (BACKGROUND_RED | BACKGROUND_BLUE)
#define COLOR_BACKGROUND_YELLOW (BACKGROUND_RED | BACKGROUND_GREEN)
#define COLOR_BACKGROUND_WHITE (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE)

typedef WORD Color;

#endif